// Blog Page Scripts
document.addEventListener('DOMContentLoaded', () => {
    loadPosts();
    loadCategories();

    // Event Listeners for Filters
    const filterButtons = document.querySelectorAll('.filter-btn');
    filterButtons.forEach(btn => {
        btn.addEventListener('click', (e) => {
            // Remove active class
            filterButtons.forEach(b => b.classList.remove('active'));
            // Add active class
            e.target.classList.add('active');

            const category = e.target.getAttribute('data-category');
            loadPosts(category);
        });
    });
});

async function loadCategories() {
    try {
        const categories = await API.getCategories();
        const filterContainer = document.querySelector('.filter-buttons');

        if (filterContainer && categories.length > 0) {
            // Keep "All" option
            let html = '<button class="filter-btn active" data-category="all">Tất cả</button>';
            html += categories.map(c => `<button class="filter-btn" data-category="${c.id}">${c.name}</button>`).join('');
            filterContainer.innerHTML = html;

            // Re-attach listeners
            const btns = filterContainer.querySelectorAll('.filter-btn');
            btns.forEach(btn => {
                btn.addEventListener('click', (e) => {
                    btns.forEach(b => b.classList.remove('active'));
                    e.target.classList.add('active');
                    const category = e.target.getAttribute('data-category');
                    loadPosts(category);
                });
            });
        }
    } catch (error) {
        console.error('Error loading categories:', error);
    }
}

async function loadPosts(categoryId = 'all') {
    const grid = document.getElementById('postsGrid');
    if (!grid) return;

    grid.innerHTML = '<div class="loading-spinner"></div>';

    try {
        const params = {
            is_published: true
        };

        if (categoryId && categoryId !== 'all') {
            // Check if it's a numeric ID or a slug. 
            // My API expects numeric ID for category_id. 
            // If the old frontend used slugs in data-category, I might need to look up.
            // But `loadCategories` above generates buttons with `data-category="${c.id}"`.
            // So we are safe if we use the buttons generated by JS.
            // However, static HTML might have buttons with slugs (e.g. data-category="digital-marketing").
            // If so, my API needs to handle finding posts by category slug or I need to fetch category by slug first.
            // Simplified: Assume I replaced static buttons with dynamic ones in `loadCategories`.
            // But `loadCategories` runs async. Initial load might use 'all'.

            // If passed a non-numeric string (slug) and not 'all', we might have issues if API expects ID.
            // Let's modify posts.php to support category_slug filtering or handled here?
            // Safer: API.getPosts can filter filtering. 
            // My posts.php currently does `p.category_id = ?`.
            // I should stick to IDs.

            params.category_id = categoryId;
        }

        const response = await API.getPosts(params);
        const posts = response.data || [];

        if (posts.length === 0) {
            grid.innerHTML = '<p class="no-posts">Chưa có bài viết nào trong danh mục này.</p>';
            return;
        }

        grid.innerHTML = '';
        posts.forEach((post, index) => {
            const card = createBlogCard(post, index);
            grid.appendChild(card);
        });

    } catch (error) {
        console.error('Error loading posts:', error);
        grid.innerHTML = '<p class="error-msg">Không thể tải bài viết.</p>';
    }
}

function createBlogCard(post, index) {
    const a = document.createElement('a');
    a.href = `/blog/${post.slug}`;
    a.className = 'post-card-link-wrapper';
    a.style.animationDelay = `${index * 100}ms`;

    const categoryColor = post.category_color || '#22C55E';
    const categoryTextColor = isLightColor(categoryColor) ? '#1F2937' : '#FFFFFF';
    let categoryTag = `<span class="post-card-category" style="background: ${categoryColor}; color: ${categoryTextColor};">${post.category_name || 'Blog'}</span>`;

    let imageHtml = '';
    if (post.featured_image) {
        imageHtml = `<div class="post-card-image" style="background-image: url('${post.featured_image}'); background-size: cover; background-position: center;">${categoryTag}</div>`;
    } else {
        imageHtml = `
            <div class="post-card-image" 
                style="background: linear-gradient(135deg, var(--color-blue) 0%, var(--color-mint) 100%); display: flex; align-items: center; justify-content: center;">
                <span style="font-size: 3rem;">📄</span>
                ${categoryTag}
            </div>
        `;
    }

    a.innerHTML = `
        <article class="clay-card post-card">
            ${imageHtml}
            <div class="post-card-body">
                <h3 class="post-card-title">${post.title}</h3>
                <p class="post-card-excerpt">${post.excerpt || ''}</p>
                 <div class="post-card-footer">
                    <span class="post-date">${formatDate(post.published_at)}</span>
                    <span class="post-read-time">${post.read_time || '5 phút đọc'}</span>
                </div>
            </div>
        </article>
    `;
    return a;
}

function formatDate(dateString) {
    if (!dateString) return '';
    return new Date(dateString).toLocaleDateString('vi-VN', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });
}

// Helper function to determine if a color is light or dark
function isLightColor(color) {
    const hex = color.replace('#', '');
    const r = parseInt(hex.substr(0, 2), 16);
    const g = parseInt(hex.substr(2, 2), 16);
    const b = parseInt(hex.substr(4, 2), 16);
    const brightness = (r * 299 + g * 587 + b * 114) / 1000;
    return brightness > 155;
}

